### ISSUE TITLE
maxSockets

### ISSUE THREAD

**Issue by sm2017** [TooTallNate/node-https-proxy-agent#105]
How can I set maxSockets?

**Comment by Rasfuranku** [comment]
Could the keepAlive parameter be included on this too?

**Comment by Rasfuranku** [comment]
There is a work around for this. As the Agent is being created with the `http.Agent` you can access to its properties and set them.

```
const httpsAgentProxyAgent = new HttpsProxyAgent("http://0.0.0.0:8080");
httpsAgentProxyAgent.maxSockets = 40;
httpsAgentProxyAgent.keepAlive = true;
```

**Comment by sm2017** [comment]
@Rasfuranku 
> As the Agent is being created with the http.Agent

How you find that it created with the htto.Agent, Can you show me the source?

**Comment by Rasfuranku** [comment]
It is using the `agent-base` library which is an `http.Agent` generator.
agent-base: https://github.com/TooTallNate/node-agent-base#readme
Magic happens here:
https://github.com/TooTallNate/node-agent-base/blob/bc0f58c1f02f545acd1a6bd887ed5b06b50874a9/src/index.ts#L91
