### ISSUE TITLE
Proxy authentication (username, password)

### ISSUE THREAD

**Issue by agarioBotDev** [TooTallNate/node-https-proxy-agent#12]
Hello,

Is the proxy authentication implemented ? Cannot find it, e.g.a proxy requires username and password else status 407 will be returned...

I would be appreciated for any help,
David

**Comment by TooTallNate** [comment]
Do _one_ of these:

### In the URI

``` js
var proxy = new HttpsProxyAgent('https://username:password@your-proxy.com');
```

### Set the `auth` option

``` js
var proxyOpts = url.parse('https://your-proxy.com');
proxyOpts.auth = 'username:password';
var proxy = new HttpsProxyAgent(proxyOpts);
```

### Set the HTTP header manually

``` js
var proxyOpts = url.parse('https://your-proxy.com');
proxyOpts.headers = {
  'Proxy-Authentication': 'Basic ' + new Buffer('username:password').toString('base64')
};
var proxy = new HttpsProxyAgent(proxyOpts);
```

**Comment by agarioBotDev** [comment]
thanks !

**Comment by okv** [comment]
Hi, there.
It would be nice to see that at readme page)

**Comment by axe312ger** [comment]
Yes please, add this to the readme/docs

@TooTallNate :)

**Comment by DuBistKomisch** [comment]
:+1: worth mentioning, assumed the options listed would be exhaustive, so had to come digging here to confirm auth works.

**Comment by aabbccsmith** [comment]
Bump :) Would be great on the readme

**Comment by jfrenl** [comment]
How to make it that it could use a txt file.

**Comment by StreetStrider** [comment]
It would be nice to have this information in the readme. It would be easier to search for `password` on package's readme page and repo's readme page. The same is already true for `socks-proxy-agent` package.

**Comment by BlueCannonBall** [comment]
> Do _one_ of these:
> ### In the URI
> 
> ```js
> var proxy = new HttpsProxyAgent('https://username:password@your-proxy.com');
> ```
> 
> ### Set the `auth` option
> 
> ```js
> var proxyOpts = url.parse('https://your-proxy.com');
> proxyOpts.auth = 'username:password';
> var proxy = new HttpsProxyAgent(proxyOpts);
> ```
> 
> ### Set the HTTP header manually
> 
> ```js
> var proxyOpts = url.parse('https://your-proxy.com');
> proxyOpts.headers = {
>   'Proxy-Authentication': 'Basic ' + new Buffer('username:password').toString('base64')
> };
> var proxy = new HttpsProxyAgent(proxyOpts);
> ```

The header is called Proxy-Authorization not Proxy-Authentication.

**Comment by fbx31** [comment]
Hi, in my company and using HttpsProxyAgent library, only the first one is working properly, aka, URI, the 2 others failed to authenticate.

**Comment by timfong888** [comment]
I am getting an openssl error, but not sure if it is due to my proxy service provider, smartproxy:

Error in audio stream for JdUVIwuNy_c: [Error: C037E8F4D43E0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:358:
