### ISSUE TITLE
ERR_UNEXPECTED_PROXY_AUTH in chrome

### ISSUE THREAD

**Issue by raDiesle** [TooTallNate/node-https-proxy-agent#16]
I am using it in combination with http-proxy-middleware
but getting ERR_UNEXPECTED_PROXY_AUTH in crhome network console.

any idea how to fix it? I tried multiple variations.

**Comment by TooTallNate** [comment]
You're trying to use this module in Chrome? I'm not sure I understand. This module implements the `http.Agent` interface for usage with Node.js' `http.Client` http request interface.

**Comment by raDiesle** [comment]
browser sync provides me the webserver, which I open an index.html in browser.
in index.html, AJAX calls are done, which I like to proxy on the webserver,
because server-side disable of cors is a security problem, but needed for development.

**Comment by TooTallNate** [comment]
You're gonna have to show me some example code because I'm still not following.

**Comment by raDiesle** [comment]
here is the full code:

gulp.task(CONFIG.GULP.DEV_WEBSERVER, function () {
        plugins.browserSync = plugins.browserSync || require(CONFIG.GULP.BROWSER_SYNC);
		plugins.HttpsProxyAgent = require('https-proxy-agent');
		plugins.proxy = plugins.proxy || require("http-proxy-middleware");
		
		
		var jsonPlaceholderProxy = plugins.proxy(
			"/etc",
			
			{
				target : "https://int-dev.cz",
				agent: new plugins.HttpsProxyAgent( {host : "proxy.corp.dir", port : "8080", secureProxy : true}),
				logLevel: 'debug',
			   changeOrigin: true, 
			}
	
		);
		
		plugins.browserSync = require('browser-sync').create();
		
        plugins.browserSync.init({
            server: {
                baseDir: CONFIG.DEV.WEBSERVER_BASE_ROOT_DIRS()
				,
				  middleware: [jsonPlaceholderProxy],
			},
            startPath: CONFIG.DEV.WEBSERVER_STARTPATH(),
            port: 3000,
			 https: true,
			 
        });
    });


Seems like problem is also described here: https://github.com/http-auth/http-auth/issues/24

Maybe you have an idea.
