### ISSUE TITLE
Options passed into HttpsProxyAgent() constructor aren't propagated to tls.connect() when switching to the TLS handshake

### ISSUE THREAD

**Issue by robertbullen** [TooTallNate/node-https-proxy-agent#35]
The options that are passed in to the constructor at index.js:25 (and eventually assigned to `this.proxy`) are not propagated to the call to `tls.connect()` at index.js:153. This means that attempting to alter TLS behavior from the default with a statement like `new HttpsProxyAgent({ rejectUnauthorized: false })` doesn't work.

I suggest a fix something like this:

```javascript
      if (opts.secureEndpoint) {
        // This line is the fix.
        opts = Object.assign({}, proxy, opts);

        // since the proxy is connecting to an SSL server, we have
        // to upgrade this socket connection to an SSL connection
        debug(
          'upgrading proxy-connected socket to TLS connection: %o',
          opts.host
        );
        opts.socket = socket;
        opts.servername = opts.servername || opts.host;
        opts.host = null;
        opts.hostname = null;
        opts.port = null;
        sock = tls.connect(opts);
      }
```

**Comment by TooTallNate** [comment]
There's two potential places to set `rejectUnauthorized`, depending on which target you want:

 * On the constructor options only applies to the connection to the proxy server (not the destination endpoint).
 * On the options to `http.request()` only applies to the destination endpoint, but not the proxy server.

Take a look at the test case code that covers this:

```js
			let proxy =
				process.env.HTTPS_PROXY ||
				process.env.https_proxy ||
				`https://localhost:${sslProxyPort}`;
			proxy = url.parse(proxy);
			proxy.rejectUnauthorized = false; // This one is for the connection to the proxy server
			let agent = new HttpsProxyAgent(proxy);

			let opts = url.parse(`https://localhost:${sslServerPort}`);
			opts.agent = agent;
			opts.rejectUnauthorized = false; // This one is for the connection to the endpoint server

			https.get(opts, function(res) {
                          // ...
```

**Comment by billypon** [comment]
@TooTallNate 

> There's two potential places to set `rejectUnauthorized`, depending on which target you want:
> 
> * On the constructor options only applies to the connection to the proxy server (not the destination endpoint).
> * On the options to `http.request()` only applies to the destination endpoint, but not the proxy server.
> 
> Take a look at [the test case code that covers this](https://github.com/TooTallNate/node-https-proxy-agent/blob/0379e01a9f1b07005260056ed44d25e9c8a097ac/test/test.js#L347-L376):
> 
> ```js
> const proxy =
>   process.env.HTTPS_PROXY ||
>   process.env.https_proxy ||
>   `https://localhost:${sslProxyPort}`;
> const proxyOpts = url.parse(proxy);
> proxyOpts.rejectUnauthorized = false; // This one is for the connection to the proxy server
> const agent = new HttpsProxyAgent(proxyOpts);
> 
> const opts = url.parse(`https://localhost:${sslServerPort}`);
> opts.agent = agent;
> opts.rejectUnauthorized = false; // This one is for the connection to the endpoint server
> 
> https.get(opts, function(res) {
>   // ...
> ```

@TooTallNate Both of two cases are not work for me.
I use `fetch`, but it doesn't implement rejectUnauthorized option.
HttpsProxyAgent dosen't implement this option too, and `proxyOpts.rejectUnauthorized = false` is not work.
