### ISSUE TITLE
"undefined is not a function" => Object.assign

### ISSUE THREAD

**Issue by Lilipi** [TooTallNate/node-https-proxy-agent#36]
When using https-proxy-agent in my context, I had this error :
> "Undefined is not a fonction at index.js:35"

After some research, I found that I had to add a new dependency to my module in order to work because Object.assign wasn't supported.

I add the module babel-polyfill and load it (`require("babel-polyfill");`) at the very beginning of my module using https-proxy-agent and it works.

I think adding this dependancy directly in your module could help some people who have same issue.

Ps: Sorry for my bad English !

**Comment by TooTallNate** [comment]
Sorry, you need to be using Node.js v4 or newer for this module.
