### ISSUE TITLE
Outdated version of debug - Snyk

### ISSUE THREAD

**Issue by knoxcard** [TooTallNate/node-https-proxy-agent#37]
Need to upgrade to the latest version of debug
https://github.com/visionmedia/debug/releases/

✗ Low severity vulnerability found on debug@2.6.8
- desc: Regular Expression Denial of Service (ReDoS)
- info: https://snyk.io/vuln/npm:debug:20170905
- from: node_services@1.0.0 > npm@5.5.1 > pacote@6.0.2 > make-fetch-happen@2.5.0 > https-proxy-agent@2.1.0 > debug@2.6.8
Your dependencies are out of date, otherwise you would be using a newer debug than debug@2.6.8.
Try deleting node_modules, reinstalling and running `snyk test` again.
If the problem persists, one of your dependencies may be bundling outdated modules.

**Comment by knoxcard** [comment]
Pull requests already submitted :-)

**Comment by TooTallNate** [comment]
2.1.1 has been released.
