### ISSUE TITLE
Need support to additional HTTP headers on opening connection to proxy

### ISSUE THREAD

**Issue by mrgiba** [TooTallNate/node-https-proxy-agent#4]
The Secure Proxy I connect to requires a <b>Proxy-Authentication</b> header whose value does not follow the <b>Basic &lt;Base 64 value&gt;</b> format. 

In order to address my current issue and also to give more flexibility in the HTTP connect request, I already have a patch that adds support to additional headers (described as a <b>headers</b> object inside the opts passed to the HttpProxyAgent)

Please let me know if that approach is acceptable, so I can send a pull request,

Thanks

**Comment by mrgiba** [comment]
Hi. Did you have a chance to look at my patch ? If that goes well, I'll start using the library in the product I work on - and be glad to give more contributions

Thanks

**Comment by TooTallNate** [comment]
Fixed in f2b10805e3385a47c78c69ccbf146b99ad5e4437.
