### ISSUE TITLE
Error: connect EINVAL

### ISSUE THREAD

**Issue by r0b5t4** [TooTallNate/node-https-proxy-agent#6]
Somehow I can not get it to work. Wget can fetch the page through the https proxy. Any advice would be greatly appreciated. Below is the console output. Many thanks.

```
using proxy server "<internal company proxy>"
attempting to GET "https://download.01.org"

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect EINVAL
    at errnoException (net.js:904:11)
    at connect (net.js:766:19)
    at net.js:845:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
```

**Comment by TooTallNate** [comment]
I need some repro code here. Also, can you try out v1.0.0 and let me know if that makes things any easier or not? Cheers!

**Comment by r0b5t4** [comment]
Got to admit my proxy address was bad, iirc the protocol (http://) was missing. Unfortunately the error only showed itself down in native code as per above.

Works a treat now, thanks. Feel free to close or use as request for better checking of the proxy address.
