### ISSUE TITLE
Please create a 2.x branch and pull in this commit and publish

### ISSUE THREAD

**Issue by AaronFriel** [TooTallNate/node-https-proxy-agent#84]
This will unblock many, many people who are unable to resolve `npm audit` errors in their CI/CD system.

https://github.com/AaronFriel/node-https-proxy-agent/commit/25d3006b5d49ed93c68ce6b684fbeb0a34e2545f

**Comment by stabback** [comment]
In case anyone else's deploys are stuck on this - https://www.npmjs.com/package/npm-force-resolutions may help you out while this is addressed, or while your dependencies update their dependencies (which may need to update their dependencies...)

1. `npm i --save-dev npm-force-resolutions`
2. Add this to your package.json
```
    "resolutions": {
        "https-proxy-agent": "^3.0.0"
    }
```
3. Let npm-force-resolutions do it's thing
```
rm -r node_modules
npx npm-force-resolutions
npm install
```
4. re-run your audit `npm audit`.

This will force your dependencies to update to 3.0.1 as of right now.  The bump from 2.2.2 to 3.0.0 can be read about here: https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0

Summary of major changes:
- Remove Node 5 and 7 from Travis: 590bc8b
- Remove Node 4 from Travis: 6c804a2

So if you're not running those versions of node, you should be fine but you should ensure your application is working before following the above advice!

Remember to get rid of this workaround as soon as either
1. The security fix is properly applied to 2.2.x
2. All of your various dependencies update their versions.

**Comment by jsphkm** [comment]
Thanks, I can confirm that this worked.  When 3.0.1+ is released, do I simply remove the resolutions script from `package.json`, (optionally) uninstall `npm-force-resolutions`, and reinstall `node_modules`?

**Comment by manoharreddyporeddy** [comment]
With above steps, it only temporarily goes away. npm i gets the issue back.

**Comment by louislva** [comment]
@TooTallNate would you be able to publish @AaronFriel's patch?

**Comment by ineffyble** [comment]
Please do this.

**Comment by neuralbrain** [comment]
When you publish your code, notice the vulnerabilities are back. (assuming asp.net core)
I have created a work-around:
1) In the directory that contains the node_modules folder, create a command file i.e. install.com (this is just a text file ).
2) Edit that file and place two commands in it: npx npm-force-resolutions (and) npm install
3) In your project file you will find <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
Replace npm install with cmd.exe install.com
should look like this: <Exec WorkingDirectory="$(SpaRoot)" Command="cmd.exe install.com" />
4) Now publish an no vulnerabilities. happy days

**Comment by XhmikosR** [comment]
https://help.github.com/en/github/managing-security-vulnerabilities/about-security-alerts-for-vulnerable-dependencies#data-sources-for-security-alerts

Someone should contact GitHub to speed things up.

**Comment by khitrenovich** [comment]
I just pinged npm security team via email, not sure what's the right way to fix GitHub audit.

**Comment by khitrenovich** [comment]
> I just pinged npm security team via email, not sure what's the right way to fix GitHub audit.

The npm advisory was just updated - 
![image](https://user-images.githubusercontent.com/3424762/67297262-ad961f00-f4b7-11e9-883c-8dbc5a3505df.png)

**Comment by TooTallNate** [comment]
Done in v2.2.3.
