### ISSUE TITLE
Update the node-agent-base version

### ISSUE THREAD

**Issue by vhpoet** [TooTallNate/node-https-proxy-agent#9]
I need [this commit](https://github.com/TooTallNate/node-agent-base/commit/777b3502a5eb4c1906000cccf5ac2bf6d1c891e4) to be able to use `https-proxy-agent` in webpack.

**Comment by TooTallNate** [comment]
Released agent-base v2.0.1 with that commit, so doing a fresh `npm install https-proxy-agent` should pick up that new version. Cheers!

**Comment by vhpoet** [comment]
@TooTallNate Thank you!!!
