### ISSUE TITLE
HttpsProxyAgent inheritance from base Agent partially broken in v4.0.0

### ISSUE THREAD

**Issue by kadler15** [TooTallNate/node-https-proxy-agent#92]
I noticed that timeouts passed to the `HttpsProxyAgent` constructor have no effect in v4.0.0. I believe the bug is a result of the [agent-base](https://github.com/TooTallNate/node-agent-base) TypeScript rewrite released in agent-base@5.0.0.

`HttpsProxyAgent` inherits prototype methods from `Agent` via [`util.inherits`](https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor), but when the `Agent` constructor is [invoked](https://github.com/TooTallNate/node-agent-base/blob/5.0.0/src/index.ts#L29), `this` refers to the `Agent` instance, not the `HttpsProxyAgent` child instance. The effect is equivalent to the parent `Agent` constructor never being called.

v2.2.4:
```
const HttpsProxyAgent = require('https-proxy-agent');
const agent = new HttpsProxyAgent({ timeout: 100 });
agent.timeout; // Result is 100
```

v4.0.0:
```
const HttpsProxyAgent = require('https-proxy-agent');
const agent = new HttpsProxyAgent({ timeout: 100 });
agent.timeout; // Result is undefined
```

**Comment by TooTallNate** [comment]
Please use v5.0.0.
